service: ${opt:service}

provider:
  name: aws
  runtime: nodejs${self:custom.runtime.${opt:stage, self:provider.stage}}
  timeout: 30
  stage: develop
  # If you want to change to a different AWS profile
  # from ~/.aws/credentials, you can do so here
  profile: default
  environment: ${file(./.env.yml):${opt:stage, self:provider.stage}}

stackTags:
  project: 'PROJECT_NAME'
  environment: ${opt:stage, self:provider.stage}
  service: ${self:service}

custom:
  serverless-offline:
    # httpsProtocol: 'dev-certs'
    port: 3000

  webpack:
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

  runtime:
    develop: '6.10'
    staging: '8.10'
    production: '8.10'

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

functions:
  ping:
    handler: src/ping.default
    events:
      - http:
          path: ping
          method: get
      # Ping every 5 minutes to avoid cold starts
      - schedule:
          rate: rate(5 minutes)
          enabled: true

# you can add CloudFormation resource templates here
# resources:
#  Resources:

plugins:
  - serverless-webpack
  - serverless-offline
